# Generated by Django 5.1.1 on 2025-02-09 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
